refact: update registry and bashlib64 (#3)
* refact: update bashlib64

* refact: update registry

diff --git a/testmansh b/testmansh
--- a/testmansh
+++ b/testmansh
@@ -100,7 +100,7 @@ TERM="${TERM:-vt100}"
 # BashLib64 / Module / Globals / Setup script run-time environment
 #######################################
 
-export BL64_VERSION='12.5.0'
+export BL64_VERSION='12.6.0'
 
 # Declare imported variables
 export LANG
@@ -231,7 +231,7 @@ export _BL64_BSH_TXT_UNSUPPORTED='BashLib64 is not supported in the current Bash
 # BashLib64 / Module / Globals / Check for conditions and report status
 #######################################
 
-export BL64_CHECK_VERSION='3.2.0'
+export BL64_CHECK_VERSION='3.3.0'
 
 export BL64_CHECK_MODULE="$BL64_VAR_OFF"
 
@@ -242,6 +242,7 @@ export _BL64_CHECK_TXT_PARAMETER_DEFAULT='required parameter value must be other
 export _BL64_CHECK_TXT_COMMAND_NOT_FOUND='required command is not present'
 export _BL64_CHECK_TXT_COMMAND_NOT_EXECUTABLE='required command is present but has no execution permission'
 export _BL64_CHECK_TXT_COMMAND_NOT_INSTALLED='required command is not installed'
+export _BL64_CHECK_TXT_COMMAND_NOT_IN_PATH='required command is not found in any of the search paths'
 
 export _BL64_CHECK_TXT_FILE_NOT_FOUND='required file is not present'
 export _BL64_CHECK_TXT_FILE_NOT_FILE='path is present but is not a regular file'
@@ -361,12 +362,14 @@ export _BL64_DBG_TXT_DEBUG='Debug'
 # BashLib64 / Module / Globals / Manage local filesystem
 #######################################
 
-export BL64_FS_VERSION='4.2.2'
+export BL64_FS_VERSION='4.3.0'
 
 export BL64_FS_MODULE="$BL64_VAR_OFF"
 
 export BL64_FS_PATH_TEMPORAL=''
 export BL64_FS_PATH_CACHE=''
+# Location for temporary files generated by bashlib64 functions
+export BL64_FS_PATH_TMP='/tmp'
 
 export BL64_FS_CMD_CHMOD=''
 export BL64_FS_CMD_CHOWN=''
@@ -406,12 +409,14 @@ export BL64_FS_SET_LN_VERBOSE=''
 export BL64_FS_SET_LS_NOCOLOR=''
 export BL64_FS_SET_MKDIR_PARENTS=''
 export BL64_FS_SET_MKDIR_VERBOSE=''
+export BL64_FS_SET_MKTEMP_DIRECTORY=''
+export BL64_FS_SET_MKTEMP_QUIET=''
+export BL64_FS_SET_MKTEMP_TMPDIR=''
 export BL64_FS_SET_MV_FORCE=''
 export BL64_FS_SET_MV_VERBOSE=''
 export BL64_FS_SET_RM_FORCE=''
 export BL64_FS_SET_RM_RECURSIVE=''
 export BL64_FS_SET_RM_VERBOSE=''
-
 
 export BL64_FS_UMASK_RW_USER='u=rwx,g=,o='
 export BL64_FS_UMASK_RW_GROUP='u=rwx,g=rwx,o='
@@ -421,16 +426,21 @@ export BL64_FS_UMASK_RW_GROUP_RO_ALL='u=rwx,g=rwx,o=rx'
 
 export BL64_FS_SAFEGUARD_POSTFIX='.bl64_fs_safeguard'
 
-export _BL64_FS_TXT_COPY_FILE_PATH='copy file'
-export _BL64_FS_TXT_CREATE_DIR_PATH='create directory'
-export _BL64_FS_TXT_MERGE_ADD_SOURCE='merge content from source'
-export _BL64_FS_TXT_RESTORE_OBJECT='restore original file from backup'
-export _BL64_FS_TXT_SAFEGUARD_FAILED='unable to safeguard requested path'
-export _BL64_FS_TXT_SAFEGUARD_OBJECT='backup original file'
+export BL64_FS_TMP_PREFIX='bl64tmp'
+
 export _BL64_FS_TXT_CLEANUP_CACHES='clean up OS cache contents'
 export _BL64_FS_TXT_CLEANUP_LOGS='clean up OS logs'
 export _BL64_FS_TXT_CLEANUP_TEMP='clean up OS temporary files'
+export _BL64_FS_TXT_COPY_FILE_PATH='copy file'
+export _BL64_FS_TXT_CREATE_DIR_PATH='create directory'
+export _BL64_FS_TXT_MERGE_ADD_SOURCE='merge content from source'
 export _BL64_FS_TXT_MERGE_DIRS='merge directories content'
+export _BL64_FS_TXT_RESTORE_OBJECT='restore original file from backup'
+export _BL64_FS_TXT_SAFEGUARD_FAILED='unable to safeguard requested path'
+export _BL64_FS_TXT_SAFEGUARD_OBJECT='backup original file'
+
+export _BL64_FS_TXT_ERROR_NOT_TMPDIR='provided directory was not created by bl64_fs_create_tmpdir'
+export _BL64_FS_TXT_ERROR_NOT_TMPFILE='provided directory was not created by bl64_fs_create_tmpfile'
 
 #######################################
 # BashLib64 / Module / Globals / Format text data
@@ -2137,6 +2147,42 @@ function bl64_check_home() {
 }
 
 #######################################
+# Check and report if the command is available using the current search path
+#
+# * standar PATH variable is used for the search
+# * aliases and built-in commands will always return true
+# * if the command is in the search path, then bl64_check_command is used to ensure it can be used
+#
+# Arguments:
+#   $1: command file name
+#   $2: Not found error message. Default: _BL64_CHECK_TXT_COMMAND_NOT_IN_PATH
+# Outputs:
+#   STDOUT: None
+#   STDERR: Error message
+# Returns:
+#   0: Command found
+#   BL64_LIB_ERROR_FILE_NOT_FOUND
+#######################################
+function bl64_check_command_search_path() {
+  bl64_dbg_lib_show_function "$@"
+  local file="${1:-}"
+  local message="${2:-${_BL64_CHECK_TXT_COMMAND_NOT_IN_PATH}}"
+  local full_path=''
+
+  bl64_check_parameter 'file' || return $?
+
+  full_path="$(type -p "${file}")"
+  # shellcheck disable=SC2181
+  if (( $? != 0)); then
+    bl64_msg_show_error "${message} (command: ${file} ${BL64_MSG_COSMETIC_PIPE} ${_BL64_CHECK_TXT_FUNCTION}: ${FUNCNAME[1]:-NONE}@${BASH_LINENO[1]:-NONE})"
+    # shellcheck disable=SC2086
+    return $BL64_LIB_ERROR_FILE_NOT_FOUND
+  fi
+
+  bl64_check_command "$full_path"
+}
+
+#######################################
 # BashLib64 / Module / Setup / Show shell debugging inlevelion
 #######################################
 
@@ -2704,6 +2750,7 @@ function _bl64_fs_set_command() {
 # Create command sets for common options
 #
 # * Warning: bootstrap function
+# * BL64_FS_SET_MKTEMP_TMPDIR: not using long form (--) as it requires =
 #
 # Arguments:
 #   None
@@ -2734,6 +2781,9 @@ function _bl64_fs_set_options() {
     BL64_FS_SET_LS_NOCOLOR='--color=never'
     BL64_FS_SET_MKDIR_PARENTS='--parents'
     BL64_FS_SET_MKDIR_VERBOSE='--verbose'
+    BL64_FS_SET_MKTEMP_DIRECTORY='--directory'
+    BL64_FS_SET_MKTEMP_QUIET='--quiet'
+    BL64_FS_SET_MKTEMP_TMPDIR='-p'
     BL64_FS_SET_MV_FORCE='--force'
     BL64_FS_SET_MV_VERBOSE='--verbose'
     BL64_FS_SET_RM_FORCE='--force'
@@ -2758,6 +2808,9 @@ function _bl64_fs_set_options() {
     BL64_FS_SET_LS_NOCOLOR='--color=never'
     BL64_FS_SET_MKDIR_PARENTS='--parents'
     BL64_FS_SET_MKDIR_VERBOSE='--verbose'
+    BL64_FS_SET_MKTEMP_DIRECTORY='--directory'
+    BL64_FS_SET_MKTEMP_QUIET='--quiet'
+    BL64_FS_SET_MKTEMP_TMPDIR='-p'
     BL64_FS_SET_MV_FORCE='--force'
     BL64_FS_SET_MV_VERBOSE='--verbose'
     BL64_FS_SET_RM_FORCE='--force'
@@ -2782,6 +2835,9 @@ function _bl64_fs_set_options() {
     BL64_FS_SET_LS_NOCOLOR='--color=never'
     BL64_FS_SET_MKDIR_PARENTS='--parents'
     BL64_FS_SET_MKDIR_VERBOSE='--verbose'
+    BL64_FS_SET_MKTEMP_DIRECTORY='--directory'
+    BL64_FS_SET_MKTEMP_QUIET='--quiet'
+    BL64_FS_SET_MKTEMP_TMPDIR='-p'
     BL64_FS_SET_MV_FORCE='--force'
     BL64_FS_SET_MV_VERBOSE='--verbose'
     BL64_FS_SET_RM_FORCE='--force'
@@ -2806,6 +2862,9 @@ function _bl64_fs_set_options() {
     BL64_FS_SET_LS_NOCOLOR='--color=never'
     BL64_FS_SET_MKDIR_PARENTS='-p'
     BL64_FS_SET_MKDIR_VERBOSE=' '
+    BL64_FS_SET_MKTEMP_DIRECTORY='-d'
+    BL64_FS_SET_MKTEMP_QUIET='-q'
+    BL64_FS_SET_MKTEMP_TMPDIR='-p'
     BL64_FS_SET_MV_FORCE='-f'
     BL64_FS_SET_MV_VERBOSE=' '
     BL64_FS_SET_RM_FORCE='-f'
@@ -2830,6 +2889,9 @@ function _bl64_fs_set_options() {
     BL64_FS_SET_LS_NOCOLOR='--color=never'
     BL64_FS_SET_MKDIR_PARENTS='-p'
     BL64_FS_SET_MKDIR_VERBOSE='-v'
+    BL64_FS_SET_MKTEMP_DIRECTORY='-d'
+    BL64_FS_SET_MKTEMP_QUIET='-q'
+    BL64_FS_SET_MKTEMP_TMPDIR='-p'
     BL64_FS_SET_MV_FORCE='-f'
     BL64_FS_SET_MV_VERBOSE='-v'
     BL64_FS_SET_RM_FORCE='-f'
@@ -3129,6 +3191,31 @@ function bl64_fs_run_chown() {
   bl64_dbg_lib_trace_start
   # shellcheck disable=SC2086
   "$BL64_FS_CMD_CHOWN" $verbose "$@"
+  bl64_dbg_lib_trace_stop
+}
+
+#######################################
+# Command wrapper with verbose, debug and common options
+#
+# * Warning: mktemp with no arguments creates a temp file by default
+#
+# Arguments:
+#   $@: arguments are passed as-is to the command
+# Outputs:
+#   STDOUT: command output
+#   STDERR: command stderr
+# Returns:
+#   command exit status
+#######################################
+function bl64_fs_run_mktemp() {
+  bl64_dbg_lib_show_function "$@"
+  local verbose="$BL64_FS_SET_MKTEMP_QUIET"
+
+  bl64_dbg_lib_command_enabled && verbose=''
+
+  bl64_dbg_lib_trace_start
+  # shellcheck disable=SC2086
+  "$BL64_FS_CMD_MKTEMP" $verbose "$@"
   bl64_dbg_lib_trace_stop
 }
 
@@ -3861,6 +3948,109 @@ function bl64_fs_set_ephemeral() {
   fi
 
   return 0
+}
+
+#######################################
+# Create temporal directory
+#
+# * Wrapper to the mktemp tool
+#
+# Arguments:
+#   None
+# Outputs:
+#   STDOUT: full path to temp dir
+#   STDERR: error messages
+# Returns:
+#   0: temp created ok
+#  >0: failed to create temp
+#######################################
+function bl64_fs_create_tmpdir() {
+  bl64_dbg_lib_show_function
+  local template="${BL64_FS_TMP_PREFIX}-${BL64_SCRIPT_NAME}.XXXXXXXXXX"
+
+  bl64_fs_run_mktemp \
+    "$BL64_FS_SET_MKTEMP_DIRECTORY" \
+    "$BL64_FS_SET_MKTEMP_TMPDIR" "$BL64_FS_PATH_TMP" \
+    "$template"
+}
+
+#######################################
+# Create temporal file
+#
+# * Wrapper to the mktemp tool
+#
+# Arguments:
+#   None
+# Outputs:
+#   STDOUT: full path to temp file
+#   STDERR: error messages
+# Returns:
+#   0: temp created ok
+#  >0: failed to create temp
+#######################################
+function bl64_fs_create_tmpfile() {
+  bl64_dbg_lib_show_function
+  local template="${BL64_FS_TMP_PREFIX}-${BL64_SCRIPT_NAME}.XXXXXXXXXX"
+
+  bl64_fs_run_mktemp \
+    "$BL64_FS_SET_MKTEMP_TMPDIR" "$BL64_FS_PATH_TMP" \
+    "$template"
+}
+
+#######################################
+# Remove temporal directory created by bl64_fs_create_tmpdir
+#
+# Arguments:
+#   $1: full path to the tmpdir
+# Outputs:
+#   STDOUT: None
+#   STDERR: error messages
+# Returns:
+#   0: temp removed ok
+#  >0: failed to remove temp
+#######################################
+function bl64_fs_rm_tmpdir() {
+  bl64_dbg_lib_show_function "$@"
+  local tmpdir="$1"
+
+  bl64_check_parameter 'tmpdir' &&
+    bl64_check_directory "$tmpdir" ||
+    return $?
+
+  if [[ "$tmpdir" != ${BL64_FS_PATH_TMP}/${BL64_FS_TMP_PREFIX}-*.* ]]; then
+    bl64_msg_show_error "${_BL64_FS_TXT_ERROR_NOT_TMPDIR} (${tmpdir})"
+    return $BL64_LIB_ERROR_TASK_FAILED
+  fi
+
+  bl64_fs_rm_full "$tmpdir"
+}
+
+#######################################
+# Remove temporal file create by bl64_fs_create_tmpfile
+#
+# Arguments:
+#   $1: full path to the tmpfile
+# Outputs:
+#   STDOUT: None
+#   STDERR: error messages
+# Returns:
+#   0: temp removed ok
+#  >0: failed to remove temp
+#######################################
+function bl64_fs_rm_tmpfile() {
+  bl64_dbg_lib_show_function "$@"
+  local tmpfile="$1"
+
+  bl64_check_parameter 'tmpfile' &&
+    bl64_check_file "$tmpfile" ||
+    return $?
+
+  if [[ "$tmpfile" != ${BL64_FS_PATH_TMP}/${BL64_FS_TMP_PREFIX}-*.* ]]; then
+    bl64_msg_show_error "${_BL64_FS_TXT_ERROR_NOT_TMPFILE} (${tmpfile})"
+    return $BL64_LIB_ERROR_TASK_FAILED
+  fi
+
+  bl64_fs_rm_file "$tmpfile"
 }
 
 #######################################
@@ -7143,8 +7333,9 @@ function bl64_vcs_github_run_api() {
   bl64_check_parameter 'api_call' ||
     return $?
 
+  # shellcheck disable=SC2086
   bl64_rxtx_run_curl \
-    "$BL64_RXTX_SET_CURL_SILENT" \
+    $BL64_RXTX_SET_CURL_SILENT \
     "${BL64_VCS_GITHUB_API_URL}/${api_call}"
 }
 
@@ -13712,7 +13903,7 @@ export TESTMANSH_DEFAULT_LINT_PATH
 export TESTMANSH_ENV
 export TESTMANSH_CMD_BATS="${TESTMANSH_CMD_BATS:-/opt/bats-core/bin/bats}"
 export TESTMANSH_CMD_SHELLCHECK="${TESTMANSH_CMD_SHELLCHECK:-/usr/bin/shellcheck}"
-export TESTMANSH_REGISTRY="${TESTMANSH_REGISTRY:-ghcr.io/serdigital64}"
+export TESTMANSH_REGISTRY="${TESTMANSH_REGISTRY:-ghcr.io/automation64}"
 export TESTMANSH_IMAGES_TEST="${TESTMANSH_IMAGES_TEST:-}"
 
 # Bats-core internal variables
